
CREATE TABLE DimProduct(
	 ProductKEY   varchar (50) NOT NULL,
	 Id   varchar (50) NULL,
	 Description   varchar (250) NULL,
	 UnitId   varchar (50) NULL,
	 UnitDescription   varchar (250) NULL,
	 ClassificationDescription   varchar (250) NULL,
	 LabourPerc   numeric (28, 14) NULL,
	 EquipmentPerc   numeric (28, 14) NULL,
	 MaterialPerc   numeric (28, 14) NULL,
	 SafetyBurdenPerc   numeric (28, 14) NULL,
	 PlannedUnitCost   numeric (28, 14) NULL,
	 CustomFieldId1   varchar (50) NULL,
	 CustomFieldDescription1   varchar (250) NULL,
	 CustomFieldId2   varchar (50) NULL,
	 CustomFieldDescription2   varchar (250) NULL,
	 CustomFieldId3   varchar (50) NULL,
	 CustomFieldDescription3   varchar (250) NULL,
	 CustomFieldId4   varchar (50) NULL,
	 CustomFieldDescription4   varchar (250) NULL,
	 CustomFieldId5   varchar (50) NULL,
	 CustomFieldDescription5   varchar (250) NULL,
	 CustomFieldId6   varchar (50) NULL,
	 CustomFieldDescription6   varchar (250) NULL,
	 CustomFieldId7   varchar (50) NULL,
	 CustomFieldDescription7   varchar (250) NULL,
	 CustomFieldId8   varchar (50) NULL,
	 CustomFieldDescription8   varchar (250) NULL,
	 CustomFieldId9   varchar (50) NULL,
	 CustomFieldDescription9   varchar (250) NULL,
	 CustomFieldId10   varchar (50) NULL,
	 CustomFieldDescription10   varchar (250) NULL,
	 CompanyId   varchar (50) NULL,
	 ProjectId   varchar (50) NULL,
	 WorkEmissionFactor   numeric (28, 14) NULL,
	 MaterialEmissionFactor   numeric (28, 14) NULL,
	 TransportEmissionFactor   numeric (28, 14) NULL,
	PRIMARY KEY(ProductKEY)
);


