
CREATE TABLE DimCustomer(
	 CustomerKEY   varchar (50) NOT NULL,
	 Id   varchar (50) NULL,
	 Description   varchar (250) NULL,
	 VatCode   varchar (50) NULL,
	 FiscalCode   varchar (50) NULL,
	 CustomerCustomFieldId1   varchar (50) NULL,
	 CustomerCustomFieldDescription1   varchar (250) NULL,
	 CustomerCustomFieldId2   varchar (50) NULL,
	 CustomerCustomFieldDescription2   varchar (250) NULL,
	 CustomerCustomFieldId3   varchar (50) NULL,
	 CustomerCustomFieldDescription3   varchar (250) NULL,
	 CustomerCustomFieldId4   varchar (50) NULL,
	 CustomerCustomFieldDescription4   varchar (250) NULL,
	 CustomerCustomFieldId5   varchar (50) NULL,
	 CustomerCustomFieldDescription5   varchar (250) NULL,
	 CustomerCustomFieldId6   varchar (50) NULL,
	 CustomerCustomFieldDescription6   varchar (250) NULL,
	 CustomerCustomFieldId7   varchar (50) NULL,
	 CustomerCustomFieldDescription7   varchar (250) NULL,
	 CustomerCustomFieldId8   varchar (50) NULL,
	 CustomerCustomFieldDescription8   varchar (250) NULL,
	 CustomerCustomFieldId9   varchar (50) NULL,
	 CustomerCustomFieldDescription9   varchar (250) NULL,
	 CustomerCustomFieldId10   varchar (50) NULL,
	 CustomerCustomFieldDescription10   varchar (250) NULL,
	 Address   varchar (250) NULL,
	 Location   varchar (50) NULL,
	 PostalCode   varchar (50) NULL,
	 ProvinceCode   varchar (50) NULL,
	 CountryCode   varchar (50) NULL,
	 Mail   varchar (50) NULL,
	 GeoPosition   varchar (50) NULL,
	PRIMARY KEY(CustomerKEY)
);

